<Workspace Version="0.9.1.4062" X="5.02992324794761" Y="46.0150347228888" zoom="0.994488700419554" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="9defb4d9-7336-4840-ac83-9da4acb7862f" type="PythonNodeModels.PythonNode" nickname="GetCoordinates" x="452.364443887178" y="445.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" inputcount="1">
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#该节点的输入内容将存储为 IN 变量中的一个列表。
dataEnteringNode = IN

point_list = []

with open(IN[0], 'r') as f:
    lines = f.readlines()
    for line in lines:
        data = line.split('\t')
        x = float(data[0].strip()) 
        y = float(data[1].strip()) 
        p = Point.ByCoordinates(x, y)
        point_list.append(p)

#将输出内容指定给 OUT 变量。
OUT = point_list</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.Filename guid="e39cbfa9-86c4-4ed3-96e7-27a87703f729" type="CoreNodeModels.Input.Filename" nickname="File Path" x="87" y="446.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.String>C:\Users\Administrator\Desktop\金鸡湖模型资料\洋红圆.txt</System.String>
    </CoreNodeModels.Input.Filename>
    <DSRevitNodesUI.Levels guid="7bde489d-be10-436d-b118-d6521ad7eec4" type="DSRevitNodesUI.Levels" nickname="Levels" x="705.999182767562" y="496.473346445973" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="4:标高 1" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4e0bb8e6-fedd-4e72-9a2b-723638869ec2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FamilyInstance.ByPointAndLevel" x="917.301163247222" y="281.310919006026" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.ByPointAndLevel@Revit.Elements.FamilyType,Autodesk.DesignScript.Geometry.Point,Revit.Elements.Level" />
    <DSRevitNodesUI.FamilyTypes guid="1cec385b-04ec-4565-a9c5-c79170271820" type="DSRevitNodesUI.FamilyTypes" nickname="Family Types" x="172.194658077894" y="225.000575835335" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" index="173:水泥土搅拌桩-插型钢:800 mm" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e39cbfa9-86c4-4ed3-96e7-27a87703f729" start_index="0" end="9defb4d9-7336-4840-ac83-9da4acb7862f" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="背景预览" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>